apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    vm.kubevirt.io/name: fedora-bronze-swordtail-41
  type: ClusterIP
